Query parsing: fully rewrite of the query parser
* Until now the parsing was mostly relying on a couple of regular
  expressions with lookbehind assertions to take into account escaped
  characters. Although they were working fine and also allowed to
  sensibly speed up the first development of gjson-py, they also had two
  major limitations:
  * Could not work in all corner cases.
  * Prevented the implementation of the GJSON features still missing in
    gjson-py.
* This commit refactors completely the parsing using a more standard
  parser approach, that allows to fine-tune the parsing much more to
  cover all corner cases and also enables the development of GJSON
  features still missing.
* There shouldn't be any difference for normal queries, but some corner
  cases might now return a proper error.
* Introduced a new GJSONParseError for parser-specific errors, than
  inherits from GJSONError and also provides a graphic way to show where
  the parsing error occurred. Example output:

    GJSONParseError: Invalid or unsupported query part `invalid`.
    Query: name.last.invalid
    -----------------^